language: go
go:
  - 1.12.x
os:
  - linux
dist: trusty
sudo: false
install: true
script:
  - env GO111MODULE=on go build -ldflags="-s -w -X github.com/bakito/smc/cmd.version=x.x.x"
  - env GO111MODULE=on go test ./... -cover
